CATEGORIE(ID_CATEGORIE,	DENUMIRE);
MAGAZIN(ID_MAGAZIN,DENUMIRE, ORAS);
PRODUCATOR(ID_PRODUCATOR,NUME,SERVICE);
PRODUS(ID_PRODUS,DENUMIRE,COD_CATEGORIE, COD_PRODUCATOR, USER_RATING);
STOC(COD_PRODUS, COD_MAGAZIN, PRET, CANTITATE);